-- SQL SubQueires Problems With Solution --

-- From the following tables, write a SQL query to find all the orders issued by the salesman 'Paul Adam'.
-- Return ord_no, purch_amt, ord_date, customer_id and salesman_id.

select * from orders 
where salesman_id =
    (select salesman_id 
    from salesman 
    where name='Paul Adam')


-- From the following tables write a SQL query to find all orders generated by London-based salespeople. 
-- Return ord_no, purch_amt, ord_date, customer_id, salesman_id.

select * from orders 
where salesman_id = 
    (select salesman_id 
    from salesman 
    where city = 'London')


-- From the following tables write a SQL query to find the order values greater than the average order value of 10th October 2012. 
-- Return ord_no, purch_amt, ord_date, customer_id, salesman_id.

select * from orders
where purch_amt > 
    (select avg(purch_amt) 
    from orders 
    where ord_date='2012-10-10')


-- From the following tables write a SQL query to determine the commission of the salespeople in Paris. Return commission.

select commission 
from salesman 
where salesman_id in
    (select salesman_id 
    from salesman 
    where city = 'Paris')


-- From the following tables write a SQL query to count the number of customers with grades above the average in New York City. 
-- Return grade and count.
select grade, count(*)
from customer
where grade > 
    (select avg(grade)
    from customer 
    where city = 'New York')
group by grade


-- From the following tables, write a SQL query to find those salespeople who earned the maximum commission. 
-- Return ord_no, purch_amt, ord_date, and salesman_id.
select ord_no, purch_amt, ord_date, salesman_id
from orders
where salesman_id in (
    select salesman_id
    from salesman 
    where commission=(
        select max(commission)
        from salesman
    )
)


-- From the following tables write a SQL query to find salespeople who had more than one customer. Return salesman_id and name.
select salesman_id, name
from salesman
where salesman_id in (
    select salesman_id
    from customer
    group by salesman_id
    having count(salesman_id)>1
)


-- From the following tables write a SQL query to find those orders, which are higher than the average amount of the orders. 
-- Return ord_no, purch_amt, ord_date, customer_id and salesman_id.
select * from orders
select ord_no, purch_amt, ord_date, customer_id, salesman_id
from orders 
where purch_amt > (
    select avg(purch_amt)
    from orders 
)


-- Write a query to extract all data from the customer table if and only if one or more of the customers 
-- in the customer table are located in London.
select * from customer c1
where exists (
    select * 
    from customer c2
    where city='London'
)
